import { Student } from "./Student";
import { Faculty } from "./Faculty";
import { Staff } from "./Staff";
var student = new Student("Anu", "Chennai");
student.study();
student.displayAddress();
console.log("----------------");
var faculty = new Faculty("Dr. Kumar", "Bangalore");
faculty.teach();
faculty.displayAddress();
console.log("----------------");
var staff = new Staff("Ravi", "Coimbatore");
staff.work();
staff.displayAddress();
